import scrapy

class ImovelItem(scrapy.Item):
    imobiliaria = scrapy.Field()
    codigo = scrapy.Field()
    url_detalhes = scrapy.Field()
    url_img = scrapy.Field()
    preco = scrapy.Field()
    bairro = scrapy.Field()
    cidade = scrapy.Field()
    tipo = scrapy.Field()
    dormitorios = scrapy.Field()
    metragem = scrapy.Field()
    vagas = scrapy.Field()
    data_captura = scrapy.Field()
    endereco = scrapy.Field()
    descricao = scrapy.Field()
    iptu = scrapy.Field()
    condominio = scrapy.Field()
    caracteristicas = scrapy.Field()